load("@buck2-haskell//:defs.bzl", "haskell_toolchain_library")
load("@toolchains//:haskell_all.bzl", "haskell_toolchain_all")

# Boot libraries
[haskell_toolchain_library(
    name = lib,
#   package_db = "/path/to/ghc/_build/stage1/lib/package.conf.d",
    visibility = ["//..."],
) for lib in [
    "array",
    "base",
    "binary",
    "bytestring",
    "containers",
    "deepseq",
    "directory",
    "exceptions",
    "filepath",
    "ghc",
    "ghc-boot",
    "os-string",
    "process",
    "text",
    "time",
    "transformers",
    "unix",
]]

# Third-party dependencies.
# Separating these from the boot libraries makes it convenient to change the
# package_db path to point to a different store.
[haskell_toolchain_library(
    name = lib,
#   package_db = "/path/to/store/ghc-9.10.3-inplace/package.db",
    visibility = ["//..."],
) for lib in [
    "aeson",
    "async",
    "extra",
    "file-io",
    "flatparse",
    "generic-lens",
    "ghc-paths",
    "grapesy",
    "hashable",
    "hedgehog",
    "lens",
    "monad-control",
    "mtl",
    "lens-family",
    "optparse-applicative",
    "proto-lens",
    "split",
    "tasty",
    "tasty-hedgehog",
    "temporary",
    "typed-process",
    "vector",
]]
