load("@buck2-haskell//:defs.bzl", "haskell_toolchain_library")
load("@toolchains//:haskell_all.bzl", "haskell_toolchain_all")

[haskell_toolchain_library(
    name = lib,
    visibility = ["//..."],
) for lib in [
    "aeson",
    "async",
    "base",
    "binary",
    "bytestring",
    "containers",
    "deepseq",
    "directory",
    "exceptions",
    "filepath",
    "file-io",
    "flatparse",
    "ghc",
    "ghc-boot",
    "ghc-paths",
    "grapesy",
    "hashable",
    "lens-family",
    "proto-lens",
    "os-string",
    "split",
    "text",
    "time",
    "transformers",
    "vector",
]]
