default_extensions = [
    "Haskell2010",
    #
    "BlockArguments",
    "DataKinds",
    "DefaultSignatures",
    "DeriveAnyClass",
    "DeriveFunctor",
    "DeriveGeneric",
    "DeriveLift",
    "DeriveTraversable",
    "DerivingStrategies",
    "DerivingVia",
    "FlexibleContexts",
    "FlexibleInstances",
    "GADTs",
    "GeneralizedNewtypeDeriving",
    "ImportQualifiedPost",
    "InstanceSigs",
    "LambdaCase",
    "MultiParamTypeClasses",
    "MultiWayIf",
    "NamedFieldPuns",
    "NegativeLiterals",
    "NoImplicitPrelude",
    "NumericUnderscores",
    "OverloadedLabels",
    "OverloadedStrings",
    "PartialTypeSignatures",
    "PatternSynonyms",
    "RankNTypes",
    "RecordWildCards",
    "RoleAnnotations",
    "ScopedTypeVariables",
    "StandaloneDeriving",
    "TypeApplications",
    "TypeFamilies",
    "UndecidableInstances",
    "ViewPatterns",
    "OverloadedRecordDot",
    "TypeOperators",
    # for some reason this is on by default???! it turns "label" into a reserved word
    "NoForeignFunctionInterface",
]

default_ghc_flags = ["-X" + ext for ext in default_extensions] + [
    # for now
    "-O0",
    # turn this on with object-determinism patch. nixified GHC is not yet with that.
    # "-fobject-determinism",
    #
    "-Weverything",
    "-Wno-missing-exported-signatures",
    "-Wno-missing-export-lists",
    "-Wno-missing-import-lists",
    "-Wno-missed-specialisations",
    "-Wno-all-missed-specialisations",
    "-Wno-unsafe",
    "-Wno-missing-local-signatures",
    "-Wno-monomorphism-restriction",
    "-Wno-prepositive-qualified-module",
    "-Wno-missing-safe-haskell-mode",
    "-fdiagnostics-color=always",
    "-Wno-unused-packages",
    "-Wno-missing-kind-signatures",
    # GHC >= 9.8 is stricter.
    "-Wno-missing-role-annotations",
    "-Wno-term-variable-capture",
    "-Wno-missing-poly-kind-signatures",
    "-Wno-x-partial",
]
