{-# LANGUAGE TemplateHaskell, CPP #-}

-- This is required because the code that's TH-generated by @switch@ in @parseOptionSpec@ reuses the binding @c@.
{-# OPTIONS_GHC -Wno-name-shadowing #-}

module Internal.DynFlags.Options where

import Control.Applicative (asum, some, (<|>))
import Control.Monad.Trans.State.Strict (State, execState)
import Data.ByteString (ByteString)
import Data.Foldable (toList)
import Data.Maybe (fromMaybe)
import FlatParse.Basic (
  Parser,
  anyAsciiDecimalInt,
  byteString,
  byteStringOf,
  char,
  eof,
  err,
  lookahead,
  skipSatisfy,
  strToUtf8,
  string,
  utf8ToStr,
  )
import FlatParse.Basic.Switch (switch)
import GHC (GeneralFlag (..), GhcLink (..))
import GHC.Data.FastString (mkFastStringByteString)
import GHC.Driver.DynFlags (DynFlags (..), Option (..), PackageArg (..), WarningFlag)
import GHC.Driver.Flags (WarningGroup, warnFlagNames, warningGroupName, warningGroups)
import GHC.Driver.Session (FlagSpec (..), fFlags, setGeneralFlag', setTmpDir, unSetGeneralFlag', updOptLevel)
import GHC.Unit (stringToUnit, stringToUnitId)
import GHC.Unit.Module.Warnings (WarningCategory (..), defaultWarningCategory)
import Internal.DynFlags.Update (
  ExtensionUpdate,
  addCppFlag,
  addExpose,
  addPackageDB,
  addWayDyn,
  addWayProf,
  resolveExtension,
  setCustomWErrorFlag,
  setCustomWarningFlag,
  setWErrorFlag,
  setWErrorWarningGroup,
  setWarningFlag,
  setWarningGroup,
  unSetCustomFatalWarningFlag,
  unSetCustomWarningFlag,
  unSetFatalWarningFlag,
  unSetFatalWarningGroup,
  unSetWarningFlag,
  unSetWarningGroup,
  updateExtension,
  updateImportPaths,
  updateLibraryPaths,
  )

eol :: Parser e ()
eol = eof <|> $(char '\n')

complete :: Parser e a -> Parser e a
complete p = p <* lookahead eol

restOfLine :: Parser e ByteString
restOfLine =
  byteStringOf (some (skipSatisfy (/= '\n')))

newtype UpdateFlags =
  UpdateFlags (DynFlags -> DynFlags)

data UpdateWithArg a b =
  UpdateWithArg {
    parser :: Parser ParseError a,
    update :: b -> UpdateFlags
  }

-- | Option definitions with their flag update function and potential argument parser.
data Opt where
  -- | An option that modifies the flags unconditionally.
  OptSwitch :: UpdateFlags -> Opt

  -- | An option that expects an argument.
  OptArg :: forall a . {
    handler :: UpdateWithArg a a,
    -- | If 'True', require either newline or @=@ between the option and its argument (@-package-db=/path@).
    -- If 'False', continue parsing after the option (@-i/path@).
    separate :: Bool
  } -> Opt

  -- | An option that can take an argument or stand on its own, like @-j@ vs @-j12@.
  -- These don't allow the argument to be separated by whitespace.
  OptArgOptional :: forall a . UpdateWithArg a (Maybe a) -> Opt

  -- | An unknown argument must be propagated to the caller because we don't have access to the actual string here.
  OptUnknown :: Opt

optSwitch :: (DynFlags -> DynFlags) -> Parser e Opt
optSwitch f = do
  lookahead eol
  pure (OptSwitch (UpdateFlags f))

argWith :: Bool -> Parser ParseError a -> (a -> DynFlags -> DynFlags) -> Parser e Opt
argWith separate parser update =
  pure OptArg {
    handler = UpdateWithArg {
      parser = parser <* lookahead eol,
      update = UpdateFlags . update
    },
    ..
  }

argString :: Bool -> (String -> DynFlags -> DynFlags) -> Parser e Opt
argString separate =
  argWith separate (utf8ToStr <$> restOfLine)

arg :: (String -> DynFlags -> DynFlags) -> Parser e Opt
arg = argString True

optionalWith :: Parser ParseError a -> (Maybe a -> DynFlags -> DynFlags) -> Parser e Opt
optionalWith parser update =
  pure $ OptArgOptional UpdateWithArg {
    parser = parser <* lookahead eol,
    update = UpdateFlags . update
  }

unknown :: Parser e Opt
unknown = pure OptUnknown

discard :: Parser e Opt
discard = arg (const id)

general :: GeneralFlag -> Parser e Opt
general = optSwitch . setGeneralFlag'

generalOff :: GeneralFlag -> Parser e Opt
generalOff = optSwitch . unSetGeneralFlag'

#if defined(MWB)

setPackageDbBytecode :: Parser e Opt
setPackageDbBytecode = general Opt_PackageDbBytecode

setDepJson :: Parser e Opt
setDepJson = arg \ v d -> d {depJSON = Just v}

#else

setPackageDbBytecode :: Parser e Opt
setPackageDbBytecode = discard

setDepJson :: Parser e Opt
setDepJson = discard

#endif

-- | We need to use an error for unknwon extensions because the update function is pure.
data ParseError =
  UnknownExtension ByteString
  |
  UnknownWarning ByteString
  deriving stock (Eq, Show)

parseExtension :: Bool -> Parser ParseError ExtensionUpdate
parseExtension disable = do
  name <- restOfLine
  case resolveExtension name disable of
    Just update -> pure update
    Nothing -> err (UnknownExtension name)

str :: String -> Parser e ()
str = complete . byteString . strToUtf8

warningGroup :: Parser e WarningGroup
warningGroup =
  asum [group <$ str (warningGroupName group) | group <- warningGroups]

warningFlag :: Parser e WarningFlag
warningFlag =
  asum [flag <$ str name | flag <- [minBound .. maxBound], name <- toList (warnFlagNames flag)]

warningCategory :: Parser e WarningCategory
warningCategory =
  defaultWarningCategory <$ $(string "warnings-deprecations")
  <|>
  custom
  where
    custom = do
      $(string "x-")
      WarningCategory . mkFastStringByteString <$> restOfLine

warnings ::
  (WarningGroup -> State DynFlags ()) ->
  (WarningFlag -> State DynFlags ()) ->
  (WarningCategory -> State DynFlags ()) ->
  Parser e Opt
warnings setGroup setFlag setCategory =
  argWith False (execState <$> parse) id
  where
    parse =
      (setGroup <$> warningGroup)
      <|>
      (setFlag <$> warningFlag)
      <|>
      (setCategory <$> warningCategory)
      <|>
      (err . UnknownWarning =<< restOfLine)

generalFlag :: Parser e GeneralFlag
generalFlag =
  asum [flagSpecFlag <$ str flagSpecName | FlagSpec {flagSpecName, flagSpecFlag} <- fFlags]

-- | This syntax is compiled to a prefix tree in @switch@, with precedence for the longest match.
--
-- The update functions are either imported from GHC or replicated here.
parseOptionSpec :: Parser ParseError Opt
parseOptionSpec =
  $(switch [|case _ of
    "f" -> general =<< generalFlag
    "fno-" -> generalOff =<< generalFlag
    -- "fobject-determinism" -> general Opt_ObjectDeterminism
    "hide-all-packages" -> general Opt_HideAllPackages
    "include-pkg-deps" -> optSwitch (\ d -> d {depIncludePkgDeps = True})
    "no-link" -> optSwitch (\ d -> d {ghcLink = NoLink})
    "dynamic" -> optSwitch addWayDyn
    "fPIC" -> general Opt_PIC
    "prof" -> optSwitch addWayProf
    "haddock" -> general Opt_Haddock
    "i" -> optionalWith restOfLine updateImportPaths
    "Werror" -> general Opt_WarnIsError
    "O" -> optionalWith anyAsciiDecimalInt (updOptLevel . fromMaybe 0)
    "osuf" -> arg (\ objectSuf_ d -> d {objectSuf_})
    "hisuf" -> arg (\ hiSuf_ d -> d {hiSuf_})
    "odir" -> arg (\ v d -> d {objectDir = Just v})
    "hidir" -> arg (\ v d -> d {hiDir = Just v})
    "stubdir" -> arg (\ v d -> d {stubDir = Just v})
    "hiedir" -> arg (\ v d -> d {hieDir = Just v})
    "dumpdir" -> arg (\ v d -> d {dumpDir = Just v})
    "this-unit-id" -> arg (\ v d -> d {homeUnitId_ = stringToUnitId v})
    "j" -> optSwitch id
    "package-env" -> arg (\ v d -> d {packageEnv = Just v})
    "dep-makefile" -> discard
    "dep-json" -> arg \ depMakefile d -> d {depMakefile}
    "main-is" -> arg (\ v d -> d {mainFunIs = Just v})
    "tmpdir" -> arg setTmpDir
    "package-db" -> arg addPackageDB
    "package-id" -> arg (\ v d -> addExpose d ("-package-id " ++ v) (UnitIdArg (stringToUnit v)))
    "package" -> arg (\ v d -> addExpose d ("-package " ++ v) (PackageArg v))
    "XNo" -> argWith False (parseExtension True) updateExtension
    "X" -> argWith False (parseExtension False) updateExtension
    "W" -> warnings setWarningGroup setWarningFlag setCustomWarningFlag
    "Wno-" -> warnings unSetWarningGroup unSetWarningFlag unSetCustomWarningFlag
    "Werror=" -> warnings setWErrorWarningGroup setWErrorFlag setCustomWErrorFlag
    "fwarn-" -> warnings unSetWarningGroup unSetWarningFlag unSetCustomWarningFlag
    "fno-warn-" -> warnings setWErrorWarningGroup setWErrorFlag setCustomWErrorFlag
    "Wwarn=" -> warnings unSetFatalWarningGroup unSetFatalWarningFlag unSetCustomFatalWarningFlag
    "Wno-error=" -> warnings unSetFatalWarningGroup unSetFatalWarningFlag unSetCustomFatalWarningFlag
    "L" -> argWith False restOfLine updateLibraryPaths
    "l" -> argString False \ v d -> d {ldInputs = d.ldInputs ++ [Option ("-l" ++ v)]}
    "D" -> argString False (addCppFlag "D")
    "U" -> argString False (addCppFlag "U")
    "fdiagnostics-color" -> discard
    _ -> unknown
  |])
