load("@buck2-haskell//:defs.bzl", "haskell_library")
load("//haskell:defs.bzl", "default_language", "default_extensions")
load("//haskell:flags.bzl", "cpp_flags_when")

flags = select({
    "root//constraints/ghc:ghc_version[ghc910]": ["mwb"],
    "root//constraints/ghc:ghc_version[ghc914]": ["unit-index"],
})

other_ghc_options = [
    "-Wall",
    "-Widentities",
    "-Wincomplete-uni-patterns",
    "-Wmissing-deriving-strategies",
    "-Wredundant-constraints",
    "-Wunused-type-patterns",
    "-Wunused-packages",
    "-O2",
]

haskell_library(
    name = "buck-worker-types",
    srcs = glob(["src/**/*.hs"]),
    compiler_flags =
        ["-X" + default_language] +
        ["-X" + ext for ext in [default_language] + default_extensions] +
        other_ghc_options +
        select_map(flags, lambda fs: cpp_flags_when("mwb" in fs, ["MWB", "UNIT_INDEX"])) +
        select_map(flags, lambda fs: cpp_flags_when("unit-index" in fs, ["UNIT_INDEX"])),
    strip_prefix = ["src"],
    deps = [
        "//haskell:aeson",
        "//haskell:base",
        "//haskell:binary",
        "//haskell:containers",
        "//haskell:exceptions",
        "//haskell:extra",
        "//haskell:filepath",
        "//haskell:ghc",
        "//haskell:ghc-paths",
        "//haskell:os-string",
        "//haskell:split",
        "//haskell:text",
    ],
    visibility = ["PUBLIC"],
    allow_worker = False,
)
