load("@buck2-haskell//:defs.bzl", "haskell_library", "haskell_binary")
load("//haskell:defs.bzl", "default_language", "default_extensions")

flags = ["mwb"]

other_extensions = []

other_common_ghc_options = [
    "-Wall",
    "-Widentities",
    "-Wincomplete-uni-patterns",
    "-Wmissing-deriving-strategies",
    "-Wredundant-constraints",
    "-Wunused-type-patterns",
    "-Wunused-packages",
]

haskell_library(
    name = "buck-proxy-lib",
    srcs = glob(["lib/**/*.hs"]),
    compiler_flags =
        ["-X" + default_language] +
        ["-X" + ext for ext in [default_language] + default_extensions] +
        other_common_ghc_options +
        ["-O2"],
    strip_prefix = ["lib"],
    deps = [
        "//haskell:base",
        "//haskell:containers",
        "//haskell:directory",
        "//haskell:grapesy",
        "//haskell:optparse-applicative",
        "//haskell:process",
        "//haskell:text",
        "//haskell:unix",
        "//grpc:buck-worker-grpc",
        "//proto:buck-worker-proto",
        "//types:buck-worker-types",
    ],
    visibility = ["PUBLIC"],
    allow_worker = False,
)

haskell_binary(
    name = "buck-proxy",
    srcs = glob(["app/**/*.hs"]),
    compiler_flags =
        ["-X" + default_language] +
        ["-X" + ext for ext in [default_language] + default_extensions] +
        other_common_ghc_options +
        ["-O2"],
    linker_flags = ["-threaded", "-with-rtsopts=\"-N -T\""],
    strip_prefix = ["app"],
    deps = [
        "//haskell:base",
        "//haskell:unix",
        "//types:buck-worker-types",
        ":buck-proxy-lib",
    ],
    visibility = ["PUBLIC"],
    allow_worker = False,
)
