load("//haskell:custom.bzl", "haskell_lib")

haskell_lib(
    name = "comparison1",
    srcs = [
        "Test1.hs",
        "Test2.hs",
        "Test3.hs",
    ],
    deps = [
        "//haskell:base",
        "//haskell:template-haskell",
    ],
)

