load("@buck2-haskell//:defs.bzl", "haskell_library", "haskell_binary")
load("//haskell:defs.bzl", "default_language", "default_extensions")
load(
    "//haskell:flags.bzl",
    "cpp_flags_when",
    "extension_flags",
    "flag_set",
)

flags = select({
    "root//constraints/ghc:ghc_version[ghc910]": ["mwb"],
    "root//constraints/ghc:ghc_version[ghc914]": [],
})

flag_config = {
    "mwb": ["-DMWB", "-DDOWNSWEEP_CACHE", "-DUNIT_INDEX"],
    "ghc-debug": ["-DGHC_DEBUG"],
    "debug": ["-D__DEBUG__"],
}

other_extensions = [
    "NoFieldSelectors",
    "OverloadedLabels",
    "QuasiQuotes",
]

other_common_ghc_options = [
    "-Wall",
    "-Widentities",
    "-Wincomplete-uni-patterns",
    "-Wmissing-deriving-strategies",
    "-Wredundant-constraints",
    "-Wunused-type-patterns",
    "-Wunused-packages",
]

haskell_library(
    name = "ghc-worker-lib",
    srcs = glob(["lib/**/*.hs"]),
    compiler_flags =
        extension_flags(default_language, default_extensions + other_extensions) +
        other_common_ghc_options +
        ["-O2"] +
        select_map(flags, lambda fs: flag_set(flag_config, fs)),
    strip_prefix = ["lib"],
    deps = [
        "//haskell:async",
        "//haskell:base",
        "//haskell:binary",
        "//haskell:bytestring",
        "//haskell:containers",
        "//haskell:deepseq",
        "//haskell:directory",
        "//haskell:file-io",
        "//haskell:ghc",
        "//haskell:grapesy",
        "//haskell:optparse-applicative",
        "//haskell:os-string",
        "//haskell:process",
        "//haskell:text",
        "//grpc:buck-worker-grpc",
        "//internal:buck-worker-internal",
        "//proto:buck-worker-proto",
        "//types:buck-worker-types",
    ] +
    select_map(flags, lambda fs: ["//haskell:ghc-debug-stub"] if "ghc-debug" in fs else []),
    visibility = ["PUBLIC"],
    allow_worker = False,
)

haskell_binary(
    name = "ghc-worker",
    srcs = glob(["app/**/*.hs"]),
    compiler_flags =
        extension_flags(default_language, default_extensions + other_extensions) +
        other_common_ghc_options +
        ["-O2"]  +
        select_map(flags, lambda fs: cpp_flags_when("mwb" in fs, ["MWB", "DOWNSWEEP_CACHE", "UNIT_INDEX"])),
    linker_flags = select({
        "prelude//os:linux": ["-O2", "-threaded", "-with-rtsopts=\"-K512M -I5 -A128M -T -N -xm40000000 -xp\""],
        "prelude//os:macos": ["-O2", "-threaded", "-with-rtsopts=\"-K512M -I5 -A128M -T -N\""],
    }),
    strip_prefix = ["app"],
    deps = [
        "//haskell:base",
        ":ghc-worker-lib",
    ],
    visibility = ["PUBLIC"],
    allow_worker = False,
)

haskell_binary(
    name = "ghc-worker-test",
    src_main = "test/Main.hs",
    srcs = glob(["test/**/*.hs"]),
    compiler_flags =
        extension_flags(default_language, default_extensions + other_extensions) +
        other_common_ghc_options +
        select_map(flags, lambda fs: flag_set(flag_config, fs)),
    linker_flags = ["-threaded", "-rtsopts", "\"-with-rtsopts=-N -T\""],
    strip_prefix = ["test"],
    deps = [
        "//haskell:base",
        "//haskell:bytestring",
        "//haskell:containers",
        "//haskell:exceptions",
        "//haskell:extra",
        "//haskell:filepath",
        "//haskell:ghc",
        "//haskell:ghc-boot",
        "//haskell:ghc-paths",
        "//haskell:hedgehog",
        "//haskell:tasty",
        "//haskell:tasty-hedgehog",
        "//haskell:text",
        ":ghc-worker-lib",
        "//internal:buck-worker-internal",
        "//test-common:ghc-worker-test-common",
        "//types:buck-worker-types",

        "//haskell:directory",
    ],
    visibility = ["PUBLIC"],
    allow_worker = False,
)

genrule(
    name = "ghc-worker-test_sh",
    srcs = [
        "run.sh.tpl",
    ],
    out = "ghc-worker-test.sh",
    bash = """
sed -e 's|%exe%|$(exe_target :ghc-worker-test)|g' run.sh.tpl > $OUT
chmod +x $OUT
    """,
)


sh_test(
    name = "test_ghc-worker-test",
    test = ":ghc-worker-test_sh",
)
