load("//haskell:custom.bzl", "haskell_lib", "haskell_bin")

haskell_lib(
    name = "worker-test-l1-lib1",
    srcs = [
        "L1_1_1.hs",
        "L1_1_2.hs",
        "L1_1_3.hs",
        "L1_1_4.hs",
    ],
    deps = [
        "//haskell:base",
        "//haskell:template-haskell",
    ],
)

haskell_lib(
    name = "worker-test-l1-lib2",
    srcs = [
        "L1_2_1.hs",
        "L1_2_2.hs",
        "L1_2_3.hs",
        "L1_2_4.hs",
    ],
    deps = [
        "//haskell:base",
        "//haskell:template-haskell",
    ],
)

haskell_lib(
    name = "worker-test-l1-lib3",
    srcs = [
        "L1_3_1.hs",
        "L1_3_2.hs",
        "L1_3_3.hs",
        "L1_3_4.hs",
    ],
    deps = [
        "//haskell:base",
        "//haskell:template-haskell",
    ],
)

haskell_lib(
    name = "worker-test-l1-lib4",
    srcs = [
        "L1_4_1.hs",
        "L1_4_2.hs",
        "L1_4_3.hs",
        "L1_4_4.hs",
    ],
    deps = [
        "//haskell:base",
        "//haskell:template-haskell",
    ],
)

haskell_lib(
    name = "worker-test-l2-lib1",
    srcs = [
        "L2_1_1.hs",
        "L2_1_2.hs",
        "L2_1_3.hs",
        "L2_1_4.hs",
    ],
    deps = [
        "//haskell:base",
        "//haskell:template-haskell",
        ":worker-test-l1-lib1",
        ":worker-test-l1-lib2",
        ":worker-test-l1-lib3",
        ":worker-test-l1-lib4",
    ],
)

haskell_lib(
    name = "worker-test-l2-lib2",
    srcs = [
        "L2_2_1.hs",
        "L2_2_2.hs",
        "L2_2_3.hs",
        "L2_2_4.hs",
    ],
    deps = [
        "//haskell:base",
        "//haskell:template-haskell",
        ":worker-test-l1-lib1",
        ":worker-test-l1-lib2",
        ":worker-test-l1-lib3",
        ":worker-test-l1-lib4",
    ],
)

haskell_lib(
    name = "worker-test-l2-lib3",
    srcs = [
        "L2_3_1.hs",
        "L2_3_2.hs",
        "L2_3_3.hs",
        "L2_3_4.hs",
    ],
    deps = [
        "//haskell:base",
        "//haskell:template-haskell",
        ":worker-test-l1-lib1",
        ":worker-test-l1-lib2",
        ":worker-test-l1-lib3",
        ":worker-test-l1-lib4",
    ],
)

haskell_lib(
    name = "worker-test-l2-lib4",
    srcs = [
        "L2_4_1.hs",
        "L2_4_2.hs",
        "L2_4_3.hs",
        "L2_4_4.hs",
    ],
    deps = [
        "//haskell:base",
        "//haskell:template-haskell",
        ":worker-test-l1-lib1",
        ":worker-test-l1-lib2",
        ":worker-test-l1-lib3",
        ":worker-test-l1-lib4",
    ],
)

haskell_lib(
    name = "worker-test-l3-lib1",
    srcs = [
        "L3_1_1.hs",
        "L3_1_2.hs",
        "L3_1_3.hs",
        "L3_1_4.hs",
    ],
    deps = [
        "//haskell:base",
        "//haskell:template-haskell",
        ":worker-test-l2-lib1",
        ":worker-test-l2-lib2",
        ":worker-test-l2-lib3",
        ":worker-test-l2-lib4",
        "//haskell:dep1",
        "//haskell:dep2",
        "//haskell:dep3",
        "//haskell:dep4",
    ],
)

haskell_lib(
    name = "worker-test-l3-lib2",
    srcs = [
        "L3_2_1.hs",
        "L3_2_2.hs",
        "L3_2_3.hs",
        "L3_2_4.hs",
    ],
    deps = [
        "//haskell:base",
        "//haskell:template-haskell",
        ":worker-test-l2-lib1",
        ":worker-test-l2-lib2",
        ":worker-test-l2-lib3",
        ":worker-test-l2-lib4",
        "//haskell:dep1",
        "//haskell:dep2",
        "//haskell:dep3",
        "//haskell:dep4",
    ],
)

haskell_lib(
    name = "worker-test-l3-lib3",
    srcs = [
        "L3_3_1.hs",
        "L3_3_2.hs",
        "L3_3_3.hs",
        "L3_3_4.hs",
    ],
    deps = [
        "//haskell:base",
        "//haskell:template-haskell",
        ":worker-test-l2-lib1",
        ":worker-test-l2-lib2",
        ":worker-test-l2-lib3",
        ":worker-test-l2-lib4",
        "//haskell:dep1",
        "//haskell:dep2",
        "//haskell:dep3",
        "//haskell:dep4",
    ],
)

haskell_lib(
    name = "worker-test-l3-lib4",
    srcs = [
        "L3_4_1.hs",
        "L3_4_2.hs",
        "L3_4_3.hs",
        "L3_4_4.hs",
    ],
    deps = [
        "//haskell:base",
        "//haskell:template-haskell",
        ":worker-test-l2-lib1",
        ":worker-test-l2-lib2",
        ":worker-test-l2-lib3",
        ":worker-test-l2-lib4",
        "//haskell:dep1",
        "//haskell:dep2",
        "//haskell:dep3",
        "//haskell:dep4",
    ],
)

