load("@buck2-haskell//:defs.bzl", "haskell_library")
load("//haskell:defs.bzl", "default_language", "default_extensions")
load("//haskell:flags.bzl", "cpp_flags_when")

flags = select({
    "root//constraints/ghc:ghc_version[ghc910]": ["mwb"],
    "root//constraints/ghc:ghc_version[ghc914]": ["unit-index"],
})

other_extensions = [
    "OverloadedLabels",
    "QuasiQuotes",
    "NoFieldSelectors",
]

other_ghc_options = [
    "-Wall",
    "-Widentities",
    "-Wincomplete-uni-patterns",
    "-Wmissing-deriving-strategies",
    "-Wredundant-constraints",
    "-Wunused-type-patterns",
    "-Wunused-packages",
]

haskell_library(
    name = "buck-worker-internal",
    srcs = glob(["src/**/*.hs"]),
    compiler_flags =
        ["-X" + default_language] +
        ["-X" + ext for ext in [default_language] + default_extensions + other_extensions] +
        other_ghc_options +
        select_map(flags, lambda fs: cpp_flags_when("mwb" in fs, ["MWB", "DOWNSWEEP_CACHE", "UNIT_INDEX", "LINKABLES"])) +
        select_map(flags, lambda fs: cpp_flags_when("downsweep-cache" in fs, ["DOWNSWEEP_CACHE"])) +
        select_map(flags, lambda fs: cpp_flags_when("unit-index" in fs, ["UNIT_INDEX"])) +
        select_map(flags, lambda fs: cpp_flags_when("linkables" in fs, ["LINKABLES"])),
    strip_prefix = ["src"],
    deps = [
        "//haskell:aeson",
        "//haskell:array",
        "//haskell:async",
        "//haskell:base",
        "//haskell:bytestring",
        "//haskell:containers",
        "//haskell:directory",
        "//haskell:exceptions",
        "//haskell:filepath",
        "//haskell:file-io",
        "//haskell:flatparse",
        "//haskell:ghc",
        "//haskell:ghc-boot",
        "//haskell:hashable",
        "//haskell:text",
        "//haskell:time",
        "//haskell:transformers",
        "//types:buck-worker-types",
    ],
    visibility = ["PUBLIC"],
    allow_worker = False,
)
