cabal-version: 2.2
name: ghc-server
version: 0.1
synopsis: Standalone GHC build server and client
license: MIT
license-file: LICENSE
build-type: Simple

flag mwb
    description: Use mwb-customized GHC from January 2026
    manual: True
    default: False

common all
  ghc-options: -Wall -Widentities -Wincomplete-uni-patterns -Wmissing-deriving-strategies -Wredundant-constraints -Wunused-type-patterns -Wunused-packages
  default-language: GHC2021
  default-extensions:
    BlockArguments,
    DataKinds,
    DerivingStrategies,
    DeriveAnyClass,
    DuplicateRecordFields,
    GADTs,
    LambdaCase,
    NamedFieldPuns,
    NoFieldSelectors,
    OverloadedLabels,
    OverloadedLists,
    OverloadedRecordDot,
    OverloadedStrings,
    QuasiQuotes,
    RecordWildCards,
    StandaloneDeriving,
    StrictData,
    TypeFamilies
  build-depends:
    base ==4.*

  if (flag(mwb))
      cpp-options: -DMWB -DDOWNSWEEP_CACHE -DUNIT_INDEX

library
  import: all
  ghc-options: -O2
  hs-source-dirs: lib
  exposed-modules:
    GhcClient.Run
    GhcServer.Build
    GhcServer.Build.Classify
    GhcServer.Build.Compile
    GhcServer.Build.Metadata
    GhcServer.Build.Propagate
    GhcServer.Build.Schedule
    GhcServer.Cabal
    GhcServer.Data.BuildEnv
    GhcServer.Data.BuildCache
    GhcServer.Data.BuildEvent
    GhcServer.Data.BuildSystem
    GhcServer.Data.Config

    GhcServer.Data.Request
    GhcServer.Data.Unit
    GhcServer.Data.UnitConfig
    GhcServer.Cache
    GhcServer.Handler
    GhcServer.Log
    GhcServer.Path
    GhcServer.Project
    GhcServer.Run
    GhcServer.Scheduler
  build-depends:
    aeson,
    async,
    buck-worker-grpc,
    buck-worker-internal,
    buck-worker-proto,
    buck-worker-types,
    bytestring,
    Cabal,
    Cabal-syntax,
    containers,
    directory,
    extra,
    file-io,
    filepath,
    ghc,
    grapesy ^>=1.0.1,
    optparse-applicative,
    stm,
    text,
    transformers

executable ghc-server
  import: all
  main-is: Main.hs
  hs-source-dirs: app/ghc-server
  ghc-options: -O2 -threaded "-with-rtsopts=-K512M -I5 -A128M -T -N"
  build-depends:
    ghc-server

executable ghc-client
  import: all
  main-is: Main.hs
  hs-source-dirs: app/ghc-client
  ghc-options: -O2 -threaded "-with-rtsopts=-K512M -I5 -A128M -T -N"
  build-depends:
    ghc-server

test-suite ghc-server-test
  import: all
  type: exitcode-stdio-1.0
  main-is: Main.hs
  hs-source-dirs: test
  ghc-options: -threaded "-with-rtsopts=-K512M -I5 -A128M -T -N"
  other-modules:
    Test.BuildTest
    Test.CabalTest
    Test.CacheTest
    Test.ScheduleTest
    Test.SchedulerTest
  build-depends:
    aeson,
    async,
    buck-worker-internal,
    buck-worker-types,
    bytestring,
    containers,
    directory,
    filepath,
    ghc,
    ghc-server,
    hedgehog,
    tasty >= 1.5,
    tasty-hedgehog,
    temporary
