name: Tests

on:
  push:
    branches:
      - tek/dev
      - tek/review-head
  pull_request:

jobs:

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable cachix
        uses: cachix/cachix-action@v17
        with:
          name: ghc-server
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Free up space
        run: rm -rf /opt/hostedtoolcache
      - name: Nix build and test
        run: nix -L build
      - name: Nix build with GHC 9.14
        run: nix -L build .#mercury-ghc9141.ghc-worker
      - name: Init Cabal
        run: nix -L develop -c cabal update
      - name: Build packages
        run: nix -L develop -c cabal build all
      - name: Run resource tests
        run: nix -L develop .#test-ext-deps -c cabal test ghc-worker --test-option='-p /resources/'
